In [2]:
import numpy

In [3]:
import scipy.special

In [4]:
class NeuralNetwork:
    #init
    def __init__(self, inputNodes, hiddenNodes, outputNodes, learningRate):
        self.activationFunction = lambda x: scipy.special.expit(x)
        self.inodes = inputNodes
        self.hnodes = hiddenNodes
        self.onodes = outputNodes
        #learning rate
        self.lr = learningRate
        #ih weights
        self.wih = (numpy.random.normal(0.0, pow(self.hnodes, -0.5),(self.hnodes, self.inodes)))
        #ho weights
        self.who = (numpy.random.normal(0.0, pow(self.onodes, -0.5),(self.onodes, self.hnodes)))
        
        pass
    #train
    def train():
        pass
    #query
    def query(self, inputsList):
        inputs = numpy.array(inputsList, ndmin=2).T #T means transpose, ndmin is min no of dimensions of array
        hiddenInputs = numpy.dot(self.wih, inputs)
        hiddenOutputs = self.activationFunction(hiddenInputs)
        finalInputs = numpy.dot(self.who, hiddenOutputs)
        finalOutputs = self.activationFunction(finalInputs)
        
        return finalOutputs
    pass

In [15]:
inp = 3
hnp = 3
onp = 3
lr = 0.3
n = NeuralNetwork(inp, hnp, onp, lr)
print(n.who)

[[-0.04457878  0.85017164  0.19096621]
 [ 0.38019084  0.27427166  0.12449865]
 [ 0.33512105 -0.79384799 -0.51650956]]
