In [1]:
import numpy

In [2]:
import scipy.special

In [9]:
class NeuralNetwork:
    #init
    def __init__(self, inputNodes, hiddenNodes, outputNodes, learningRate):
        self.activationFunction = lambda x: scipy.special.expit(x)
        self.inodes = inputNodes
        self.hnodes = hiddenNodes
        self.onodes = outputNodes
        #learning rate
        self.lr = learningRate
        #ih weights
        self.wih = (numpy.random.normal(0.0, pow(self.hnodes, -0.5),(self.hnodes, self.inodes)))
        #ho weights
        self.who = (numpy.random.normal(0.0, pow(self.onodes, -0.5),(self.onodes, self.hnodes)))
        
        pass
    #train
    def train(self, inputsList, targetsList):
        inputs = numpy.array(inputsList, ndmin=2).T
        targets = numpy.array(targetsList, ndmin=2).T#T means transpose, ndmin is min no of dimensions of array
        hiddenInputs = numpy.dot(self.wih, inputs)
        hiddenOutputs = self.activationFunction(hiddenInputs)
        finalInputs = numpy.dot(self.who, hiddenOutputs)
        finalOutputs = self.activationFunction(finalInputs)
        outputErrors = targets - finalOutputs
        hiddenErrors = numpy.dot(self.who.T, finalErrors)
        self.who += self.lr*numpy.dot((outputErrors*finalOutputs*(1.0-finalOutputs)), numpy.transpose(hiddenOutputs))
        self.wih += self.lr*numpy.dot((hiddenErrors*hiddenOutputs*(1.0-hiddenOutputs)), numpy.transpose(inputs))
        pass
    #query
    def query(self, inputsList):
        inputs = numpy.array(inputsList, ndmin=2).T #T means transpose, ndmin is min no of dimensions of array
        hiddenInputs = numpy.dot(self.wih, inputs)
        hiddenOutputs = self.activationFunction(hiddenInputs)
        finalInputs = numpy.dot(self.who, hiddenOutputs)
        finalOutputs = self.activationFunction(finalInputs)
        
        return finalOutputs
    pass

In [5]:
inp = 3
hnp = 3
onp = 3
lr = 0.3
n = NeuralNetwork(inp, hnp, onp, lr)
print(n.who)

[[-0.92565018  0.56216268 -0.24000249]
 [-0.61245775 -0.73844407 -0.20677683]
 [-0.32451232 -1.042486   -0.01270123]]


In [6]:
n.query([0.5, 0.3, -0.7])

array([[ 0.47557042],
       [ 0.32138856],
       [ 0.32217116]])